version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/careerconDbBeta
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_HOST=redis://redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - rabbitmq
      - redis

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  #rabbitmq:
  #  image: rabbitmq:management
  #  container_name: rabbitmq
  #  ports:
  #    - "15672:15672"  # RabbitMQ management UI
  #    - "5672:5672"    # RabbitMQ main port
  #  networks:
  #    - my-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
